version: "2"
services:
  web:
    image: nginx
    ports:
      - 5000:80
    working_dir: /var/www/html
    volumes:
        - ".:/var/www/html"
        - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:7.2-fpm-stretch
    working_dir: /var/www/html
    volumes:
        - ".:/var/www/html"